name: Run network tests

on:
  workflow_dispatch:
  schedule:
    - cron: '33 */3 * * *'

jobs:
  test-suite:
    name: Run test suite
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        network: ['testnet', 'devnet-malort']
    steps:
      - name: Clone network configs
        uses: actions/checkout@v3
        with:
          repository: dashevo/dash-network-configs
          token: ${{ secrets.GH_PAT }}

      - name: Install yq
        run: |
          mkdir -p ~/.local/bin
          wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -O ~/.local/bin/yq
          chmod +x ~/.local/bin/yq
          echo "~/.local/bin" >> $GITHUB_PATH

      - name: Configure network variables
        run: |
          echo "FAUCET_PRIVATE_KEY=$(yq .faucet_privkey ${{ matrix.network }}.yml)" > .env
          echo "DPNS_OWNER_PRIVATE_KEY=$(yq .dpns_hd_private_key ${{ matrix.network }}.yml)" >> .env
          echo "DASHPAY_OWNER_PRIVATE_KEY=$(yq .dashpay_hd_private_key ${{ matrix.network }}.yml)" >> .env
          echo "FEATURE_FLAGS_OWNER_PRIVATE_KEY=$(yq .feature_flags_hd_private_key ${{ matrix.network }}.yml)" >> .env
          echo "DAPI_SEED=$(awk -F '[= ]' '/^masternode/ {print $5}' ${{ matrix.network }}.inventory | awk NF | shuf -n1)" >> .env
          if [[ "${{ matrix.network }}" == "devnet"* ]]; then
            NETWORK_TYPE=devnet
            DEVNET_NAME=${{ matrix.network }}
            INSIGHT_URL="http://insight.${DEVNET_NAME#devnet-}.networks.dash.org:3001/insight-api/sync"
          else
            NETWORK_TYPE=testnet
            INSIGHT_URL="https://testnet-insight.dashevo.org/insight-api/sync"
          fi
          echo "NETWORK=$NETWORK_TYPE" >> .env
          echo "SKIP_SYNC_BEFORE_HEIGHT=$(curl -s $INSIGHT_URL | jq '.height - 200')" >> .env

      - name: Run platform test suite
        run: |
          docker run \
          -v $(pwd)/.env:/platform/packages/platform-test-suite/.env \
          dashpay/platform-test-suite:latest \
          yarn run test:suite

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # smoke-tests:
  #   name: Run smoke tests
  #   runs-on: ubuntu-20.04
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       network: ['testnet', 'devnet-malort']
  #   steps:
  #     - name: Clone network configs
  #       uses: actions/checkout@v3
  #       with:
  #         repository: dashevo/dash-network-configs
  #         token: ${{ secrets.GH_PAT }}

  #     - name: Download network deploy tool wrapper
  #       run: |
  #         mkdir -p ~/.local/bin
  #         curl -fsSL -o ~/.local/bin/dash-network https://raw.github.com/dashevo/dash-network-deploy/master/bin/dash-network
  #         chmod +x ~/.local/bin/dash-network

  #     - name: Run smoke tests
  #       run: ~/.local/bin/dash-network test testnet