name: Run testnet tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '33 */3 * * *'

# todo: matrix run against testnet + devnets based on networks specified in config repo
jobs:
  smoke-tests:
    name: Run smoke tests
    runs-on: ubuntu-20.04
    steps:
      - name: Clone network configs
        uses: actions/checkout@v3
        with:
          repository: dashevo/dash-network-configs
          token: ${{ secrets.GH_PAT }}

      - name: Download network deploy tool wrapper
        run: |
          mkdir -p ~/.local/bin
          curl -fsSL -o ~/.local/bin/dash-network https://raw.github.com/dashpay/dash-network-deploy/master/bin/dash-network
          chmod +x ~/.local/bin/dash-network

      - name: Run smoke tests
        run: |
          cd ~/dash-network-configs
          ~/.local/bin/dash-network test testnet
          
  test-suite:
    name: Run test suite
    runs-on: ubuntu-20.04
    steps:
      - name: Clone network configs
        uses: actions/checkout@v3
        with:
          repository: dashevo/dash-network-configs
          token: ${{ secrets.GH_PAT }}
          path: dash-network-configs

      - name: Read network variables
        uses: mikefarah/yq@v4
        with:
          cmd: yq '.dpns_hd_private_key' 'dash-network-configs/testnet.yml'

      - name: Debug .env file
        run: cat .env

      - name: Run platform test suite
        run: |
          docker run \
          -v $(pwd)/.env:/platform/packages/platform-test-suite/.env \
          strophy/platform-test-suite:latest \
          yarn run test:suite

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3